package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/nmonterroso/cowsay-slackapp/models"
)

/*OauthRedirectOK proper processing of an oauth accept/deny

swagger:response oauthRedirectOK
*/
type OauthRedirectOK struct {

	// In: body
	Payload *models.OauthComplete `json:"body,omitempty"`
}

// Create OauthRedirectOK with default headers values
func NewOauthRedirectOK() OauthRedirectOK {
	return OauthRedirectOK{}
}

// WriteResponse to the client
func (o *OauthRedirectOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*OauthRedirectDefault Unexpected error

swagger:response oauthRedirectDefault
*/
type OauthRedirectDefault struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// Create OauthRedirectDefault with default headers values
func NewOauthRedirectDefault() OauthRedirectDefault {
	return OauthRedirectDefault{}
}

// WriteResponse to the client
func (o *OauthRedirectDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
