package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/nmonterroso/cowsay-slackapp/models"
)

/*OauthRedirectNoContent proper processing of an oauth accept/deny

swagger:response oauthRedirectNoContent
*/
type OauthRedirectNoContent struct {
}

// Create OauthRedirectNoContent with default headers values
func NewOauthRedirectNoContent() OauthRedirectNoContent {
	return OauthRedirectNoContent{}
}

// WriteResponse to the client
func (o *OauthRedirectNoContent) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(204)
}

/*OauthRedirectDefault Unexpected error

swagger:response oauthRedirectDefault
*/
type OauthRedirectDefault struct {

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// Create OauthRedirectDefault with default headers values
func NewOauthRedirectDefault() OauthRedirectDefault {
	return OauthRedirectDefault{}
}

// WriteResponse to the client
func (o *OauthRedirectDefault) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
