package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
	"github.com/go-swagger/go-swagger/strfmt"
)

/*OauthComplete OauthComplete oauth complete

swagger:model OauthComplete
*/
type OauthComplete struct {

	/* Authorized authorized

	Required: true
	*/
	Authorized bool `json:"authorized,omitempty"`
}

// Validate validates this oauth complete
func (m *OauthComplete) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthorized(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OauthComplete) validateAuthorized(formats strfmt.Registry) error {

	if err := validate.Required("authorized", "body", bool(m.Authorized)); err != nil {
		return err
	}

	return nil
}
